BeanSceneSystem/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using BeanSceneSystem.Data;
using BeanSceneSystem.Models;
using BeanSceneSystem.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Transactions;

namespace BeanSceneSystem.Controllers
{
    public class EventController : Controller
    {
        BeanSceneSystemDbContext _context;
        IEventServices IEServices;

        public EventController(BeanSceneSystemDbContext Context, IEventServices ieServices)
        {
            _context = Context;
            IEServices = ieServices;
        }

        public IActionResult Index()
        {
            return View(IEServices.GetAllEvents());
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Event E_obj)
        {
            IEServices.CreateEvent(E_obj);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Delete(int? id)
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Event E_obj)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    _context.Event.Update(E_obj);
                    transaction.Commit();
                }
                catch
                {
                    _context.Remove(E_obj);
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Event e = _context.Event.FirstOrDefault(_e => _e.Id == id);
            if (e != null)
            {
                _context.Remove(e);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BeanSceneSystem/Controllers/MemberGuestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using BeanSceneSystem.Data;
using BeanSceneSystem.Models;
using BeanSceneSystem.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Transactions;

namespace BeanSceneSystem.Controllers
{
    public class MemberGuestController : Controller
    {
        BeanSceneSystemDbContext _context;
        IMemberGuestServices IMGServices;

        public MemberGuestController(BeanSceneSystemDbContext Context, IMemberGuestServices imgServices)
        {
            _context = Context;
            IMGServices = imgServices;
        }

        public IActionResult Index()
        {
            return View(IMGServices.GetAllMemberGuests());
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MemberGuest MG_obj)
        {
            IMGServices.CreateMemberGuest(MG_obj);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Delete(int? id)
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MemberGuest MG_obj)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    _context.MemberGuest.Update(MG_obj);
                    transaction.Commit();
                }
                catch
                {
                    _context.Remove(MG_obj);
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            MemberGuest mg = _context.MemberGuest.FirstOrDefault(_mg => _mg.Id == id);
            if (mg != null)
            {
                _context.Remove(mg);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BeanSceneSystem/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using BeanSceneSystem.Data;
using BeanSceneSystem.Models;
using BeanSceneSystem.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Transactions;

namespace BeanSceneSystem.Controllers
{
    public class ReservationController : Controller
    {
        BeanSceneSystemDbContext _context;
        IReservationServices IRServices;

        public ReservationController(BeanSceneSystemDbContext db, IReservationServices irServices)
        {
            _context = db;
            IRServices = irServices;
        }
        public IActionResult Index()
        {
            return View(IRServices.GetAllReservations());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reservation R_obj)
        {
            IRServices.CreateReservation(R_obj);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Delete(int? id)
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Reservation R_obj)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    _context.Reservation.Update(R_obj);
                    transaction.Commit();
                }
                catch
                {
                    _context.Remove(R_obj);
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            Reservation r = _context.Reservation.FirstOrDefault(_r => _r.Id == id);
            if (r != null)
            {
                _context.Remove(r);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BeanSceneSystem/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using BeanSceneSystem.Services;
using BeanSceneSystem.Models;
using Microsoft.AspNetCore.Authorization;

namespace BeanSceneSystem.Controllers
{
    public class UserController : Controller
    {

        private readonly IUserService _authService;

        public UserController(IUserService authService)
        {
            _authService = authService;
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            model.Role = "admin";
            var result = await _authService.RegisterAsync(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(RegistrationModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            model.Role = "admin";
            var result = await _authService.RegisterAsync(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await _authService.LoginAsync(model);
            if (result.StatusCode == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }
        }

        //Logout
        //[Authorize]
        public async Task<IActionResult> Logout()
        {
            await this._authService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }

        // Go to Change Password page with no provided data.
        public IActionResult ChangePassword()
        {
            return View();
        }

        // Go to Change password page with provided data and subsequent validation.
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await _authService.ChangePasswordAsync(model, User.Identity.Name);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(ChangePassword));
        }
    }
}

BeanSceneSystem/Views/Shared/_Layout.cshtml
@{
    string userName = User.Identity.Name;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeanSceneSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    @*<link rel="stylesheet" href="~/css/BootstrapTheme.css"/>*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4AA1B5; color: #FFFFFF">
        <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="MemberGuest" asp-action="Index">Members/Guests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
            </li>
            @if (User.IsInRole("admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="CreateUser">Create User</a>
                </li>
            }

           
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            </ul>
            <ul>
            @if (string.IsNullOrEmpty(userName))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="Registration">Register</a>

                </li>
             }
            </ul>
            
            <ul>
                @if (!string.IsNullOrEmpty(userName))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="ChangePassword">Forgot Password</a>
                    </li>
                }
            </ul>

           
            <form class="d-flex">
            <input class="form-control me-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            </div>
           </div>
       </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_ViewNotification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white" style="background-color: #4AA1B5; position: absolute; bottom: 5%; width: 100%;">
        <div class="container">
            &copy; 2022 - BeanSceneSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: #FFFFFF;">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BeanSceneSystem/Views/Shared/_ViewNotification.cshtml
@if (TempData["success"]!=null)
{
    <h5 class="text-sm-end btn btn-outline-primary mx-3">@TempData["success"]</h5>
}
@if (TempData["msg"] !=null)
{
    <h5 class="text-sm-end btn btn-outline-primary mx-3">@TempData["msg"] </h5>
}

@if (TempData["error"]!=null)
{
    <h5 class="text-sm-end btn btn-outline-primary mx-3">@TempData["success"]</h5>
}